# Generated by Django 4.0.10 on 2023-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdata",
            name="symbol",
            field=models.CharField(max_length=12),
        ),
    ]
