# Generated by Django 4.0.10 on 2023-02-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=6)),
                ("date", models.DateField()),
                ("open_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "financial_data",
            },
        ),
        migrations.AddIndex(
            model_name="financialdata",
            index=models.Index(fields=["symbol"], name="financial_d_symbol_7d9836_idx"),
        ),
        migrations.AddIndex(
            model_name="financialdata",
            index=models.Index(fields=["date"], name="financial_d_date_3d81f5_idx"),
        ),
        migrations.AddConstraint(
            model_name="financialdata",
            constraint=models.UniqueConstraint(
                fields=("symbol", "date"), name="unique_symbol_date"
            ),
        ),
    ]
